# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

aliases:
  - &environment
      docker:
        # specify the version you desire here
        - image: cimg/node:16.20-browsers
      resource_class: xlarge
        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
      working_directory: ~/user-sync

  - &restore_dep_cache
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  - &save_dep_cache
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

  - &build
      name: Unit tests
      command: npm run build

  - &build_steps
    - checkout
    - restore_cache: *restore_dep_cache
    - run: npm ci
    - save_cache: *save_dep_cache
    - run: *build

version: 2
jobs:
  build:
    <<: *environment
    steps: *build_steps

workflows:
  version: 2
  commit:
    jobs:
      - build

experimental:
  pipelines: true
